# Use the official Node.js image as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy the application files to the working directory
COPY . .

# Command to run the application
CMD ["node", "countup.js"]
